version: "3.9"

services:

  app:
    image: github-users:latest
    environment:
      -  SPRING_REDIS_HOST=redis
    ports:
      - "8080:8080"
      - "8081:8081"

  redis:
    image: redis:7
    command: [
      "redis-server",
      "--save", "15", "1",
    ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  redis_data:
